// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/tslib.es6 ../../../core/Collection ../../../core/collectionUtils ../../../core/Error ../../../core/reactiveUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/arrayUtils ../../../core/has ../../../core/accessorSupport/decorators/subclass ../../../geometry/support/scaleUtils ../engine/Container ../support/HighlightOptions ../../layers/support/ClipRect ../../layers/support/Geometry ../../layers/support/Path".split(" "),
function(k,e,l,m,n,d,f,y,z,A,p,q,r,t,u,v,w){const h=l.ofType({key:"type",base:null,typeMap:{rect:u,path:w,geometry:v}});k.LayerView2DMixin=c=>{c=class extends c{constructor(){super(...arguments);this.attached=!1;this.clips=new h;this.lastUpdateId=-1;this.visibleAtCurrentScale=this.updateRequested=this.moving=!1;this.highlightOptions=null}initialize(){const b=this.view?.spatialReferenceLocked??!0;this.view?.spatialReference&&b&&!this.spatialReferenceSupported?this.addResolvingPromise(Promise.reject(new n("layerview:spatial-reference-incompatible",
"The spatial reference of this layer does not meet the requirements of the view",{layer:this.layer}))):(this.container||(this.container=new r.Container),this.container.fadeTransitionEnabled=!0,this.container.visible=!1,this.container.endTransitions(),this.addHandles([d.watch(()=>this.suspended,a=>{this.container&&(this.container.visible=!a);this.view&&!a&&this.updateRequested&&this.view.requestUpdate()},d.syncAndInitial),d.watch(()=>this.layer?.opacity??1,a=>{this.container&&(this.container.opacity=
a)},d.syncAndInitial),d.watch(()=>this.layer&&"blendMode"in this.layer?this.layer.blendMode:"normal",a=>{this.container&&(this.container.blendMode=a)},d.syncAndInitial),d.watch(()=>this.layer&&"effect"in this.layer?this.layer.effect:null,a=>{this.container&&(this.container.effect=a)},d.syncAndInitial),d.watch(()=>this.highlightOptions,a=>this.container.highlightOptions=a,d.syncAndInitial),d.on(()=>this.clips,"change",()=>{this.container&&(this.container.clips=this.clips)},d.syncAndInitial),d.watch(()=>
({scale:this.view?.scale,scaleRange:this.layer&&"effectiveScaleRange"in this.layer?this.layer.effectiveScaleRange:null}),({scale:a})=>{a=null!=a?this.isVisibleAtScale(a):!1;a!==this.visibleAtCurrentScale&&this._set("visibleAtCurrentScale",a)},d.syncAndInitial)],"constructor"),this.view?.whenLayerView?this.view.whenLayerView(this.layer).then(a=>{a===this&&this.processAttach()},()=>{}):this.when().then(()=>{this.processAttach()},()=>{}))}destroy(){this.processDetach();this.updateRequested=!1}get spatialReferenceSupported(){const b=
this.view?.spatialReference;return null==b||this.supportsSpatialReference(b)}get updating(){return this.spatialReferenceSupported&&(!this.attached||!this.suspended&&(this.updateRequested||this.isUpdating())||!!this._updatingHandles?.updating)}processAttach(){this.isResolved()&&!this.attached&&!this.destroyed&&this.spatialReferenceSupported&&(this.attach(),this.attached=!0,this.requestUpdate())}processDetach(){this.attached&&(this.attached=!1,this.removeHandles("attach"),this.detach(),this.updateRequested=
!1)}isVisibleAtScale(b){const a=this.layer&&"effectiveScaleRange"in this.layer?this.layer.effectiveScaleRange:null;if(!a)return!0;const {minScale:g,maxScale:x}=a;return q.isInScaleRange(b,g,x)}requestUpdate(){this.destroyed||this.updateRequested||(this.updateRequested=!0,this.suspended||this.view.requestUpdate())}processUpdate(b){this.isFulfilled()&&!this.isResolved()?this.updateRequested=!1:(this._set("updateParameters",b),this.updateRequested&&!this.suspended&&(this.updateRequested=!1,this.update(b)))}hitTest(b,
a){return Promise.resolve(null)}supportsSpatialReference(b){return!0}canResume(){return this.spatialReferenceSupported?super.canResume()?this.visibleAtCurrentScale:!1:!1}getSuspendInfo(){const b=super.getSuspendInfo(),a=!this.spatialReferenceSupported,g=this.visibleAtCurrentScale;a&&(b.spatialReferenceNotSupported=a);g&&(b.outsideScaleRange=g);return b}addAttachHandles(b){this.addHandles(b,"attach")}};e.__decorate([f.property()],c.prototype,"attached",void 0);e.__decorate([f.property({type:h,set(b){b=
m.referenceSetter(b,this._get("clips"),h);this._set("clips",b)}})],c.prototype,"clips",void 0);e.__decorate([f.property()],c.prototype,"container",void 0);e.__decorate([f.property()],c.prototype,"moving",void 0);e.__decorate([f.property({readOnly:!0})],c.prototype,"spatialReferenceSupported",null);e.__decorate([f.property({readOnly:!0})],c.prototype,"updateParameters",void 0);e.__decorate([f.property()],c.prototype,"updateRequested",void 0);e.__decorate([f.property()],c.prototype,"updating",null);
e.__decorate([f.property()],c.prototype,"view",void 0);e.__decorate([f.property({readOnly:!0})],c.prototype,"visibleAtCurrentScale",void 0);e.__decorate([f.property({type:t})],c.prototype,"highlightOptions",void 0);return c=e.__decorate([p.subclass("esri.views.2d.layers.LayerView2D")],c)};Object.defineProperty(k,Symbol.toStringTag,{value:"Module"})});