// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../vectorTiles/style/StyleDefinition ../definitions ../enums ../number ./WGLBrush ../../../../webgl/enums".split(" "),function(E,F,A,D,K,L,p){const G=1/65536;class M extends L{constructor(){super(...arguments);this._fillProgramOptions={id:!1,pattern:!1};this._outlineProgramOptions={id:!1}}dispose(){}drawMany(h,u){const {displayLevel:k,drawPhase:c,renderPass:g,spriteMosaic:e,styleLayerUID:m}=h;var a=!1;for(var l of u)if(l.layerData.has(m)){var q=l.layerData.get(m);if(0<q.fillIndexCount||
0<q.outlineIndexCount){a=!0;break}}if(a){a=h.styleLayer;var f=a.getPaintProperty("fill-pattern");q=(l=void 0!==f)&&f.isDataDriven;if(l&&!q){var r=f.getValue(k);r=e.getMosaicItemPosition(r,!0)}f=!l&&a.getPaintValue("fill-antialias",k);var x=!0,v=1;if(!l){var w=a.getPaintProperty("fill-color"),y=a.getPaintProperty("fill-opacity");w?.isDataDriven||y?.isDataDriven||(v=a.getPaintValue("fill-color",k),v=a.getPaintValue("fill-opacity",k)*v[3],1<=v&&(x=!1))}if(!x||"opaque"!==g){var b;c===D.WGLDrawPhase.HITTEST&&
(b=K.u32to4Xu8(m+1));w=a.getPaintValue("fill-translate",k);y=a.getPaintValue("fill-translate-anchor",k);(x||"translucent"!==g)&&this._drawFill(h,m,a,u,w,y,l,r,q,b);r=!a.hasDataDrivenOutlineColor&&a.outlineUsesFillColor&&1>v;f&&"opaque"!==g&&!r&&this._drawOutline(h,m,a,u,w,y,b)}}}_drawFill(h,u,k,c,g,e,m,a,l,q){if(!m||l||null!=a){var {context:f,displayLevel:r,state:x,drawPhase:v,painter:w,pixelRatio:y,spriteMosaic:b,requestRender:B,allowDelayedRender:C}=h;h=k.fillMaterial;var d=w.vectorTilesMaterialManager,
t=y>A.vtlHighResCutoff?2:1,H=v===D.WGLDrawPhase.HITTEST,z=this._fillProgramOptions;z.id=H;z.pattern=m;d=d.getMaterialProgram(f,h,z);if(C&&null!=B&&!d.compiled)B();else{f.useProgram(d);null!=a&&({page:a}=a,z=b.getPageSize(a),null!=z&&(b.bind(f,p.TextureSamplingMode.LINEAR,a,A.vtlTextureBindingUnitSprites),d.setUniform2fv("u_mosaicSize",z),d.setUniform1i("u_texture",A.vtlTextureBindingUnitSprites)));d.setUniformMatrix3fv("u_displayMat3",e===F.TranslateAnchor.VIEWPORT?x.displayMat3:x.displayViewMat3);
d.setUniform2fv("u_fillTranslation",g);d.setUniform1f("u_depth",k.z+G);H&&d.setUniform4fv("u_id",q);g=-1;for(const n of c)if(n.layerData.has(u)&&(n.key.level!==g&&(g=n.key.level,h.setDataUniforms(d,r,k,g,b)),c=n.layerData.get(u),c.fillIndexCount&&(c.prepareForRendering(f),e=c.fillVAO,null!=e))){f.bindVAO(e);d.setUniformMatrix3fv("u_dvsMat3",n.transforms.dvs);f.setStencilFunction(p.CompareFunction.EQUAL,n.stencilRef,255);m&&d.setUniform1f("u_patternFactor",n.rangeX/(t*n.width*Math.max(2**(Math.round(r)-
n.key.level),1)));if(l){e=c.patternMap;if(!e)continue;for(const [I,J]of e)e=b.getPageSize(I),null!=e&&(b.bind(f,p.TextureSamplingMode.LINEAR,I,A.vtlTextureBindingUnitSprites),d.setUniform2fv("u_mosaicSize",e),d.setUniform1i("u_texture",A.vtlTextureBindingUnitSprites),f.drawElements(p.PrimitiveType.TRIANGLES,J[1],p.DataType.UNSIGNED_INT,Uint32Array.BYTES_PER_ELEMENT*J[0]))}else f.drawElements(p.PrimitiveType.TRIANGLES,c.fillIndexCount,p.DataType.UNSIGNED_INT,Uint32Array.BYTES_PER_ELEMENT*c.fillIndexStart);
n.triangleCount+=c.fillIndexCount/3}}}}_drawOutline(h,u,k,c,g,e,m){const {context:a,displayLevel:l,state:q,drawPhase:f,painter:r,pixelRatio:x,spriteMosaic:v,requestRender:w,allowDelayedRender:y}=h;h=k.outlineMaterial;var b=r.vectorTilesMaterialManager;const B=.75/x,C=f===D.WGLDrawPhase.HITTEST,d=this._outlineProgramOptions;d.id=C;b=b.getMaterialProgram(a,h,d);if(y&&null!=w&&!b.compiled)w();else{a.useProgram(b);b.setUniformMatrix3fv("u_displayMat3",e===F.TranslateAnchor.VIEWPORT?q.displayMat3:q.displayViewMat3);
b.setUniform2fv("u_fillTranslation",g);b.setUniform1f("u_depth",k.z+G);b.setUniform1f("u_outline_width",B);C&&b.setUniform4fv("u_id",m);g=-1;for(const t of c)t.layerData.has(u)&&(t.key.level!==g&&(g=t.key.level,h.setDataUniforms(b,l,k,g,v)),c=t.layerData.get(u),c.prepareForRendering(a),c.outlineIndexCount&&(e=c.outlineVAO,null!=e&&(a.bindVAO(e),b.setUniformMatrix3fv("u_dvsMat3",t.transforms.dvs),a.setStencilFunction(p.CompareFunction.EQUAL,t.stencilRef,255),a.drawElements(p.PrimitiveType.TRIANGLES,
c.outlineIndexCount,p.DataType.UNSIGNED_INT,Uint32Array.BYTES_PER_ELEMENT*c.outlineIndexStart),t.triangleCount+=c.outlineIndexCount/3)))}}}E.WGLBrushVTLFill=M;Object.defineProperty(E,Symbol.toStringTag,{value:"Module"})});