// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/vec2f32 ../../vectorTiles/decluttering/config ../../vectorTiles/style/StyleDefinition ../definitions ../enums ../GeometryUtils ../number ./WGLBrush ../../../../webgl/enums".split(" "),function(J,K,L,m,D,F,M,O,P,n){const Q=1/65536;class R extends P{constructor(){super(...arguments);this._iconProgramOptions={id:!1,sdf:!1};this._sdfProgramOptions={id:!1};this._spritesTextureSize=K.create()}dispose(){}drawMany(k,a){const {drawPhase:c,styleLayerUID:g}=k,f=k.styleLayer;
let d;c===F.WGLDrawPhase.HITTEST&&(d=O.u32to4Xu8(g+1));this._drawIcons(k,f,a,d);this._drawText(k,f,a,d)}_drawIcons(k,a,c,g){const {context:f,displayLevel:d,drawPhase:r,painter:p,spriteMosaic:G,state:v,styleLayerUID:y,requestRender:t,allowDelayedRender:z}=k,C=a.iconMaterial;var h=p.vectorTilesMaterialManager,w=!1;for(var A of c)if(A.layerData.has(y)){var e=A.layerData.get(y);if(0<e.iconPerPageElementsMap.size){w=!0;break}}if(w){w=a.getPaintValue("icon-translate",d);A=a.getPaintValue("icon-translate-anchor",
d);var q=a.getLayoutValue("icon-rotation-alignment",d);q===m.RotationAlignment.AUTO&&(q=a.getLayoutValue("symbol-placement",d)===m.SymbolPlacement.POINT?m.RotationAlignment.VIEWPORT:m.RotationAlignment.MAP);var b=q===m.RotationAlignment.MAP;b=a.getLayoutValue("icon-keep-upright",d)&&b;var E=e.isIconSDF;e=r===F.WGLDrawPhase.HITTEST;var B=this._iconProgramOptions;B.id=e;B.sdf=E;h=h.getMaterialProgram(f,C,B);if(z&&null!=t&&!h.compiled)t();else{f.useProgram(h);h.setUniformMatrix3fv("u_displayViewMat3",
q===m.RotationAlignment.MAP?v.displayViewMat3:v.displayMat3);h.setUniformMatrix3fv("u_displayMat3",A===m.TranslateAnchor.VIEWPORT?v.displayMat3:v.displayViewMat3);h.setUniform2fv("u_iconTranslation",w);h.setUniform1f("u_depth",a.z);h.setUniform1f("u_mapRotation",M.degToByte(v.rotation));h.setUniform1f("u_keepUpright",b?1:0);h.setUniform1f("u_level",10*d);h.setUniform1i("u_texture",D.vtlTextureBindingUnitSprites);h.setUniform1f("u_fadeDuration",L.fadeDuration/1E3);e&&h.setUniform4fv("u_id",g);g=-1;
for(const u of c)if(u.layerData.has(y)&&(u.key.level!==g&&(g=u.key.level,C.setDataUniforms(h,d,a,g,G)),e=u.layerData.get(y),0!==e.iconPerPageElementsMap.size&&(e.prepareForRendering(f),e.updateOpacityInfo(),c=e.iconVAO,null!=c))){f.bindVAO(c);h.setUniformMatrix3fv("u_dvsMat3",u.transforms.dvs);h.setUniform1f("u_time",(performance.now()-e.lastOpacityUpdate)/1E3);for(const [H,I]of e.iconPerPageElementsMap)this._renderIconRange(k,h,I,H,u)}}}}_renderIconRange(k,a,c,g,f){const {context:d,spriteMosaic:r}=
k;this._spritesTextureSize[0]=r.getWidth(g)/4;this._spritesTextureSize[1]=r.getHeight(g)/4;a.setUniform2fv("u_mosaicSize",this._spritesTextureSize);r.bind(d,n.TextureSamplingMode.LINEAR,g,D.vtlTextureBindingUnitSprites);this._setStencilState(k,f);d.drawElements(n.PrimitiveType.TRIANGLES,c[1],n.DataType.UNSIGNED_INT,Uint32Array.BYTES_PER_ELEMENT*c[0]);f.triangleCount+=c[1]/3}_drawText(k,a,c,g){const {context:f,displayLevel:d,drawPhase:r,glyphMosaic:p,painter:G,pixelRatio:v,spriteMosaic:y,state:t,styleLayerUID:z,
requestRender:C,allowDelayedRender:h}=k,w=a.textMaterial,A=G.vectorTilesMaterialManager;var e=!1;for(var q of c)if(q.layerData.has(z)){var b=q.layerData.get(z);if(0<b.glyphPerPageElementsMap.size){e=!0;break}}if(e&&(b=a.getPaintProperty("text-opacity"),!b||b.isDataDriven||0!==b.getValue(d))){b=a.getPaintProperty("text-color");var E=!b||b.isDataDriven||0<b.getValue(d)[3];b=a.getPaintProperty("text-halo-width");e=a.getPaintProperty("text-halo-color");var B=(!b||b.isDataDriven||0<b.getValue(d))&&(!e||
e.isDataDriven||0<e.getValue(d)[3]);if(E||B){b=a.getLayoutValue("text-rotation-alignment",d);b===m.RotationAlignment.AUTO&&(b=a.getLayoutValue("symbol-placement",d)===m.SymbolPlacement.POINT?m.RotationAlignment.VIEWPORT:m.RotationAlignment.MAP);e=b===m.RotationAlignment.MAP;e=a.getLayoutValue("text-keep-upright",d)&&e;q=r===F.WGLDrawPhase.HITTEST;var u=.8*3/v;this._glyphTextureSize||(this._glyphTextureSize=K.fromValues(p.width/4,p.height/4));var H=a.getPaintValue("text-translate",d),I=a.getPaintValue("text-translate-anchor",
d),N=this._sdfProgramOptions;N.id=q;var l=A.getMaterialProgram(f,w,N);if(h&&null!=C&&!l.compiled)C();else{f.useProgram(l);l.setUniformMatrix3fv("u_displayViewMat3",b===m.RotationAlignment.MAP?t.displayViewMat3:t.displayMat3);l.setUniformMatrix3fv("u_displayMat3",I===m.TranslateAnchor.VIEWPORT?t.displayMat3:t.displayViewMat3);l.setUniform2fv("u_textTranslation",H);l.setUniform1f("u_depth",a.z+Q);l.setUniform2fv("u_mosaicSize",this._glyphTextureSize);l.setUniform1f("u_mapRotation",M.degToByte(t.rotation));
l.setUniform1f("u_keepUpright",e?1:0);l.setUniform1f("u_level",10*d);l.setUniform1i("u_texture",D.vtlTextureBindingUnitGlyphs);l.setUniform1f("u_antialiasingWidth",u);l.setUniform1f("u_fadeDuration",L.fadeDuration/1E3);q&&l.setUniform4fv("u_id",g);g=-1;for(const x of c)x.layerData.has(z)&&(x.key.level!==g&&(g=x.key.level,w.setDataUniforms(l,d,a,g,y)),b=x.layerData.get(z),0!==b.glyphPerPageElementsMap.size&&(b.prepareForRendering(f),b.updateOpacityInfo(),c=b.textVAO,null!=c&&(f.bindVAO(c),l.setUniformMatrix3fv("u_dvsMat3",
x.transforms.dvs),this._setStencilState(k,x),c=(performance.now()-b.lastOpacityUpdate)/1E3,l.setUniform1f("u_time",c),b.glyphPerPageElementsMap.forEach((S,T)=>{this._renderGlyphRange(f,S,T,p,l,B,E,x)}))))}}}}_renderGlyphRange(k,a,c,g,f,d,r,p){g.bind(k,n.TextureSamplingMode.LINEAR,c,D.vtlTextureBindingUnitGlyphs);d&&(f.setUniform1f("u_halo",1),k.drawElements(n.PrimitiveType.TRIANGLES,a[1],n.DataType.UNSIGNED_INT,Uint32Array.BYTES_PER_ELEMENT*a[0]),p.triangleCount+=a[1]/3);r&&(f.setUniform1f("u_halo",
0),k.drawElements(n.PrimitiveType.TRIANGLES,a[1],n.DataType.UNSIGNED_INT,Uint32Array.BYTES_PER_ELEMENT*a[0]),p.triangleCount+=a[1]/3)}_setStencilState(k,a){const {context:c,is3D:g,stencilSymbols:f}=k;c.setStencilTestEnabled(!0);f?(c.setStencilWriteMask(255),c.setStencilFunction(n.CompareFunction.ALWAYS,a.stencilRef,255)):(c.setStencilWriteMask(0),g?c.setStencilFunction(n.CompareFunction.EQUAL,a.stencilRef,255):c.setStencilFunction(n.CompareFunction.GREATER,255,255))}}J.WGLBrushVTLSymbol=R;Object.defineProperty(J,
Symbol.toStringTag,{value:"Module"})});