// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("../../../../../chunks/vec4f32 ../DefaultVertexAttributeLayouts ./WGLBrush ../shaders/BackgroundPrograms ../shaders/TileInfoPrograms ../../../../webgl/BufferObject ../../../../webgl/enums ../../../../webgl/ProgramTemplate ../../../../webgl/Texture ../../../../webgl/TextureDescriptor ../../../../webgl/VertexArrayObject ../../../../webgl/capabilities/isWebGL2Context".split(" "),function(q,h,r,k,l,m,e,n,t,u,p,v){class w extends r{constructor(){super(...arguments);this._color=q.fromValues(1,0,
0,1)}dispose(){this._outlineProgram?.dispose();this._outlineProgram=null;this._tileInfoProgram?.dispose();this._tileInfoProgram=null;this._outlineVertexArrayObject?.dispose();this._outlineVertexArrayObject=null;this._tileInfoVertexArrayObject?.dispose();this._canvas=this._tileInfoVertexArrayObject=null}prepareState({context:b}){b.setBlendingEnabled(!0);b.setBlendFunctionSeparate(e.BlendFactor.ONE,e.BlendFactor.ONE_MINUS_SRC_ALPHA,e.BlendFactor.ONE,e.BlendFactor.ONE_MINUS_SRC_ALPHA);b.setColorMask(!0,
!0,!0,!0);b.setStencilWriteMask(0);b.setStencilTestEnabled(!1)}draw(b,a){const {context:c,requestRender:d,allowDelayedRender:g}=b;if(a.isReady)if(this._loadWGLResources(c),!g||null==d||this._outlineProgram.compiled&&this._tileInfoProgram.compiled){c.bindVAO(this._outlineVertexArrayObject);c.useProgram(this._outlineProgram);this._outlineProgram.setUniformMatrix3fv("u_dvsMat3",a.transforms.dvs);this._outlineProgram.setUniform2f("u_coord_range",a.rangeX,a.rangeY);this._outlineProgram.setUniform1f("u_depth",
0);this._outlineProgram.setUniform4fv("u_color",this._color);c.drawArrays(e.PrimitiveType.LINE_STRIP,0,4);if(b=this._getTexture(c,a))c.bindVAO(this._tileInfoVertexArrayObject),c.useProgram(this._tileInfoProgram),c.bindTexture(b,0),this._tileInfoProgram.setUniformMatrix3fv("u_dvsMat3",a.transforms.dvs),this._tileInfoProgram.setUniform1f("u_depth",0),this._tileInfoProgram.setUniform2f("u_coord_ratio",a.rangeX/a.width,a.rangeY/a.height),this._tileInfoProgram.setUniform2f("u_delta",8,8),this._tileInfoProgram.setUniform2f("u_dimensions",
b.descriptor.width,b.descriptor.height),c.drawArrays(e.PrimitiveType.TRIANGLE_STRIP,0,4);c.bindVAO()}else d()}_loadWGLResources(b){if(!this._outlineProgram||!this._tileInfoProgram){var a=n.createProgram(b,k.background),c=n.createProgram(b,l.tileInfo),d=new Int8Array([0,0,1,0,1,1,0,1]);d=m.BufferObject.createVertex(b,e.Usage.STATIC_DRAW,d);d=new p.VertexArrayObject(b,k.background.attributes,h.Pos2b,{geometry:d});var g=new Int8Array([0,0,1,0,0,1,1,1]);g=m.BufferObject.createVertex(b,e.Usage.STATIC_DRAW,
g);b=new p.VertexArrayObject(b,l.tileInfo.attributes,h.Pos2b,{geometry:g});this._outlineProgram=a;this._tileInfoProgram=c;this._outlineVertexArrayObject=d;this._tileInfoVertexArrayObject=b}}_getTexture(b,a){if(a.texture&&a.triangleCountReportedInDebug===a.triangleCount)return a.texture;a.triangleCountReportedInDebug=a.triangleCount;this._canvas||(this._canvas=document.createElement("canvas"),this._canvas.setAttribute("id","tileCanvas2d"),this._canvas.setAttribute("width","300"),this._canvas.setAttribute("height",
"32"),this._canvas.setAttribute("style","display:none"));var c=a.triangleCount;let d=a.key.id;0<a.triangleCount&&(d+=`, ${c}`);const g=this._canvas,f=g.getContext("2d");f.font="24px sans-serif";f.textAlign="left";f.textBaseline="top";f.clearRect(0,0,300,32);1E5<c?(f.fillStyle="red",f.fillRect(0,0,300,32),f.fillStyle="black"):(f.clearRect(0,0,300,32),f.fillStyle="blue");f.fillText(d,0,0);c=new u.TextureDescriptor;c.wrapMode=e.TextureWrapMode.CLAMP_TO_EDGE;c.samplingMode=e.TextureSamplingMode.NEAREST;
c.isImmutable=v(b.gl);a.texture=new t.Texture(b,c,g);return a.texture}}return w});