// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define(["../definitions","./WGLBrush","../materialKey/MaterialKey","../../../../webgl/enums"],function(k,p,q,h){class r extends p{constructor(){super(...arguments);this._computeDesc=new Map}prepareState({context:a},c){c&&c.includes("hittest")?a.setBlendFunctionSeparate(h.BlendFactor.ONE,h.BlendFactor.ONE,h.BlendFactor.ONE,h.BlendFactor.ONE):a.setBlendFunctionSeparate(h.BlendFactor.ONE,h.BlendFactor.ONE_MINUS_SRC_ALPHA,h.BlendFactor.ONE,h.BlendFactor.ONE_MINUS_SRC_ALPHA);a.setBlendingEnabled(!0);a.setColorMask(!0,
!0,!0,!0);a.setStencilWriteMask(0);a.setStencilTestEnabled(!0)}draw(a,c,b){var d=this.getGeometryType();c.commit(a);d=c.getGeometry(d);null!=d&&(a.timeline.begin(this.name),a.attributeView.bindTextures(a.context),a.context.setStencilFunction(h.CompareFunction.EQUAL,c.stencilRef,255),d.forEachCommand(e=>{const g=q.MaterialKeyBase.load(e.materialKey).symbologyType;this.supportsSymbology(g)&&this.drawGeometry(a,c,e,b)}))}_setSharedUniforms(a,c,b){const {displayLevel:d,pixelRatio:e,state:g,passOptions:f}=
c;null!=f&&"hittest"===f.type&&(a.setUniform2fv("u_hittestPos",f.position),a.setUniform1f("u_hittestDist",f.distance));a.setUniform1f("u_pixelRatio",e);a.setUniformMatrix3fv("u_tileMat3",b.transforms.tileMat3);a.setUniformMatrix3fv("u_viewMat3",g.viewMat3);a.setUniformMatrix3fv("u_dvsMat3",b.transforms.dvs);a.setUniformMatrix3fv("u_displayViewMat3",g.displayViewMat3);a.setUniform1f("u_currentZoom",Math.floor(d*k.minMaxZoomPrecisionFactor));a.setUniform1i("u_attributeTextureSize",c.attributeView.size);
a.setUniform1i("u_attributeData0",k.textureBindingAttributeData0);a.setUniform1i("u_attributeData1",k.textureBindingAttributeData1);a.setUniform1i("u_attributeData2",k.textureBindingAttributeData2);a.setUniform1i("u_attributeData3",k.textureBindingAttributeData3);a.setUniform1i("u_attributeData4",k.textureBindingAttributeData4);a.setUniform1i("u_attributeData5",k.textureBindingAttributeData5)}_setSizeVVUniforms(a,c,b,d){a.vvSizeMinMaxValue&&c.setUniform4fv("u_vvSizeMinMaxValue",b.vvSizeMinMaxValue);
a.vvSizeScaleStops&&c.setUniform1f("u_vvSizeScaleStopsValue",b.vvSizeScaleStopsValue);a.vvSizeFieldStops&&(d=b.getSizeVVFieldStops(d.key.level),null!=d&&(c.setUniform1fv("u_vvSizeFieldStopsValues",d.values),c.setUniform1fv("u_vvSizeFieldStopsSizes",d.sizes)));a.vvSizeUnitValue&&c.setUniform1f("u_vvSizeUnitValueWorldToPixelsRatio",b.vvSizeUnitValueToPixelsRatio)}_setColorAndOpacityVVUniforms(a,c,b){a.vvColor&&(c.setUniform1fv("u_vvColorValues",b.vvColorValues),c.setUniform4fv("u_vvColors",b.vvColors));
a.vvOpacity&&(c.setUniform1fv("u_vvOpacityValues",b.vvOpacityValues),c.setUniform1fv("u_vvOpacities",b.vvOpacities))}_setRotationVVUniforms(a,c,b){a.vvRotation&&c.setUniform1f("u_vvRotationType","geographic"===b.vvMaterialParameters.vvRotationType?0:1)}_getTriangleDesc(a,c,b=["a_pos"]){const d=c.bufferLayouts.geometry;b=b.map(f=>d.findIndex(l=>l.name===f));a=`${a}-${b.join("-")}`;var e=this._computeDesc.get(a);if(!e){e=c.strides;const f=c.strides.geometry,l=new Map(c.attributes);var g=d.map(m=>({...m}));
c=Math.max(...c.attributes.values());g={geometry:g};let n=0;for(const m of b)b=d[m],g.geometry.push({count:b.count,name:b.name+"1",divisor:b.divisor,normalized:b.normalized,offset:f+b.offset,stride:f,type:b.type}),g.geometry.push({count:b.count,name:b.name+"2",divisor:b.divisor,normalized:b.normalized,offset:2*f+b.offset,stride:f,type:b.type}),l.set(b.name+"1",c+ ++n),l.set(b.name+"2",c+ ++n);e={bufferLayouts:g,attributes:l,strides:e};this._computeDesc.set(a,e)}return e}}return r});