// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ./index ./array2 ./dom ./guid ./key ./loadable ./action ./icon ./loader ./popover".split(" "),function(k,f,n,g,r,t,l,u,v,w,x){function p(){"undefined"!==typeof customElements&&["calcite-action-menu","calcite-action","calcite-icon","calcite-loader","calcite-popover"].forEach(a=>{switch(a){case "calcite-action-menu":customElements.get(a)||customElements.define(a,q);break;case "calcite-action":customElements.get(a)||u.defineCustomElement();break;case "calcite-icon":customElements.get(a)||
v.defineCustomElement();break;case "calcite-loader":customElements.get(a)||w.defineCustomElement();break;case "calcite-popover":customElements.get(a)||x.defineCustomElement()}})}const m={tooltip:"tooltip",trigger:"trigger"},y=["ArrowUp","ArrowDown","End","Home"],q=f.proxyCustomElement(class extends f.H{constructor(){super();this.__registerHost();this.__attachShadow();this.calciteActionMenuOpen=f.createEvent(this,"calciteActionMenuOpen",6);this.actionElements=[];this.guid=`calcite-action-menu-${r.guid()}`;
this.menuId=`${this.guid}-menu`;this.menuButtonId=`${this.guid}-menu-button`;this.connectMenuButtonEl=()=>{const {menuButtonId:a,menuId:b,open:d,label:e}=this,c=this.slottedMenuButtonEl||this.defaultMenuButtonEl;this.menuButtonEl!==c&&(this.disconnectMenuButtonEl(),this.menuButtonEl=c,this.setTooltipReferenceElement(),c&&(c.active=d,c.setAttribute("aria-controls",b),c.setAttribute("aria-expanded",g.toAriaBoolean(d)),c.setAttribute("aria-haspopup","true"),c.id||(c.id=a),c.label||(c.label=e),c.text||
(c.text=e),c.addEventListener("pointerdown",this.menuButtonClick),c.addEventListener("keydown",this.menuButtonKeyDown)))};this.disconnectMenuButtonEl=()=>{const {menuButtonEl:a}=this;a&&(a.removeEventListener("pointerdown",this.menuButtonClick),a.removeEventListener("keydown",this.menuButtonKeyDown))};this.setMenuButtonEl=a=>{this.slottedMenuButtonEl=a.target.assignedElements({flatten:!0}).filter(b=>b?.matches("calcite-action"))[0];this.connectMenuButtonEl()};this.setDefaultMenuButtonEl=a=>{this.defaultMenuButtonEl=
a;this.connectMenuButtonEl()};this.handleCalciteActionClick=()=>{this.open=!1;this.setFocus()};this.menuButtonClick=a=>{g.isPrimaryPointerButton(a)&&this.toggleOpen()};this.updateTooltip=a=>{this.tooltipEl=a.target.assignedElements({flatten:!0}).filter(b=>b?.matches("calcite-tooltip"))[0];this.setTooltipReferenceElement()};this.setTooltipReferenceElement=()=>{const {tooltipEl:a,expanded:b,menuButtonEl:d,open:e}=this;a&&(a.referenceElement=b||e?null:d)};this.updateAction=(a,b)=>{const {guid:d,activeMenuItemIndex:e}=
this,c=`${d}-action-${b}`;a.tabIndex=-1;a.setAttribute("role","menuitem");a.id||(a.id=c);a.toggleAttribute("data-active",b===e)};this.updateActions=a=>{a?.forEach(this.updateAction)};this.handleDefaultSlotChange=a=>{this.actionElements=a.target.assignedElements({flatten:!0}).filter(b=>b?.matches("calcite-action"))};this.menuButtonKeyDown=a=>{const {key:b}=a,{actionElements:d,activeMenuItemIndex:e,open:c}=this;if(d.length){if(t.isActivationKey(b)){a.preventDefault();if(!c){this.toggleOpen();return}const h=
d[e];h?h.click():this.toggleOpen(!1)}"Tab"===b?this.open=!1:"Escape"===b?(this.toggleOpen(!1),a.preventDefault()):this.handleActionNavigation(a,b,d)}};this.handleActionNavigation=(a,b,d)=>{if(this.isValidKey(b,y))if(a.preventDefault(),this.open)"Home"===b&&(this.activeMenuItemIndex=0),"End"===b&&(this.activeMenuItemIndex=d.length-1),a=this.activeMenuItemIndex,"ArrowUp"===b&&(this.activeMenuItemIndex=n.getRoundRobinIndex(Math.max(a-1,-1),d.length)),"ArrowDown"===b&&(this.activeMenuItemIndex=n.getRoundRobinIndex(a+
1,d.length));else{this.toggleOpen();if("Home"===b||"ArrowDown"===b)this.activeMenuItemIndex=0;if("End"===b||"ArrowUp"===b)this.activeMenuItemIndex=d.length-1}};this.toggleOpenEnd=()=>{this.setFocus();this.el.removeEventListener("calcitePopoverOpen",this.toggleOpenEnd)};this.toggleOpen=(a=!this.open)=>{this.el.addEventListener("calcitePopoverOpen",this.toggleOpenEnd);this.open=a};this.appearance="solid";this.expanded=!1;this.label=this.flipPlacements=void 0;this.open=!1;this.overlayPositioning="absolute";
this.placement="auto";this.menuButtonEl=this.scale=void 0;this.activeMenuItemIndex=-1}componentWillLoad(){l.setUpLoadableComponent(this)}componentDidLoad(){l.setComponentLoaded(this)}disconnectedCallback(){this.disconnectMenuButtonEl()}expandedHandler(){this.open=!1;this.setTooltipReferenceElement()}openHandler(a){this.activeMenuItemIndex=this.open?0:-1;this.menuButtonEl&&(this.menuButtonEl.active=a);this.calciteActionMenuOpen.emit();this.setTooltipReferenceElement()}closeCalciteActionMenuOnClick(a){g.isPrimaryPointerButton(a)&&
!a.composedPath().includes(this.el)&&(this.open=!1)}activeMenuItemIndexHandler(){this.updateActions(this.actionElements)}async setFocus(){await l.componentFocusable(this);return g.focusElement(this.menuButtonEl)}renderMenuButton(){const {appearance:a,label:b,scale:d,expanded:e}=this;return f.h("slot",{name:m.trigger,onSlotchange:this.setMenuButtonEl},f.h("calcite-action",{appearance:a,class:"default-trigger",icon:"ellipsis",scale:d,text:b,textEnabled:e,ref:this.setDefaultMenuButtonEl}))}renderMenuItems(){const {actionElements:a,
activeMenuItemIndex:b,open:d,menuId:e,menuButtonEl:c,label:h,placement:z,overlayPositioning:A,flipPlacements:B}=this;return f.h("calcite-popover",{flipPlacements:B,focusTrapDisabled:!0,label:h,offsetDistance:0,open:d,overlayPositioning:A,placement:z,pointerDisabled:!0,referenceElement:c},f.h("div",{"aria-activedescendant":a[b]?.id||null,"aria-labelledby":c?.id,class:"menu",id:e,onClick:this.handleCalciteActionClick,role:"menu",tabIndex:-1},f.h("slot",{onSlotchange:this.handleDefaultSlotChange})))}render(){return f.h(f.Fragment,
null,this.renderMenuButton(),this.renderMenuItems(),f.h("slot",{name:m.tooltip,onSlotchange:this.updateTooltip}))}isValidKey(a,b){return!!b.find(d=>d===a)}get el(){return this}static get watchers(){return{expanded:["expandedHandler"],open:["openHandler"],activeMenuItemIndex:["activeMenuItemIndexHandler"]}}static get style(){return":host{box-sizing:border-box;display:flex;flex-direction:column;font-size:var(--calcite-font-size-1);color:var(--calcite-ui-text-2)}.menu ::slotted(calcite-action){margin:0.125rem;display:flex;outline-color:transparent}.menu ::slotted(calcite-action[data-active]){outline:2px solid var(--calcite-ui-focus-color, var(--calcite-ui-brand));outline-offset:calc(\n            2px *\n            calc(\n              1 -\n              2 * clamp(\n                0,\n                var(--calcite-ui-focus-offset-invert),\n                1\n              )\n            )\n          );outline-offset:0px}.default-trigger{position:relative;block-size:100%;flex:0 1 auto;align-self:stretch}slot[name\x3dtrigger]::slotted(calcite-action),calcite-action::slotted([slot\x3dtrigger]){position:relative;block-size:100%;flex:0 1 auto;align-self:stretch}.menu{flex-direction:column;flex-wrap:nowrap;outline:2px solid transparent;outline-offset:2px}:host([hidden]){display:none}[hidden]{display:none}"}},
[1,"calcite-action-menu",{appearance:[513],expanded:[516],flipPlacements:[16],label:[1],open:[1540],overlayPositioning:[513,"overlay-positioning"],placement:[513],scale:[513],menuButtonEl:[32],activeMenuItemIndex:[32],setFocus:[64]},[[9,"pointerdown","closeCalciteActionMenuOnClick"]]]);p();k.ActionMenu=q;k.SLOTS=m;k.defineCustomElement=p});