// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ./index ./dom ./loadable ./locale ./t9n ./icon".split(" "),function(n,b,p,e,f,d,q){function g(){"undefined"!==typeof customElements&&["calcite-handle","calcite-icon"].forEach(a=>{switch(a){case "calcite-handle":customElements.get(a)||customElements.define(a,r);break;case "calcite-icon":customElements.get(a)||q.defineCustomElement()}})}const r=b.proxyCustomElement(class extends b.H{constructor(){super();this.__registerHost();this.__attachShadow();this.calciteHandleNudge=b.createEvent(this,
"calciteHandleNudge",6);this.calciteInternalHandleChange=b.createEvent(this,"calciteInternalHandleChange",6);this.handleKeyDown=a=>{switch(a.key){case " ":this.activated=!this.activated;a.preventDefault();break;case "ArrowUp":if(!this.activated)break;a.preventDefault();this.calciteHandleNudge.emit({direction:"up"});break;case "ArrowDown":this.activated&&(a.preventDefault(),this.calciteHandleNudge.emit({direction:"down"}))}};this.handleBlur=()=>{this.activated=!1};this.activated=!1;this.defaultMessages=
this.effectiveLocale=this.messageOverrides=this.label=this.setSize=this.setPosition=this.messages=this.dragHandle=void 0}handleAriaTextChange(){const a=this.getAriaText("live");a&&this.calciteInternalHandleChange.emit({message:a})}onMessagesChange(){}connectedCallback(){d.connectMessages(this);f.connectLocalized(this)}async componentWillLoad(){e.setUpLoadableComponent(this);await d.setUpMessages(this)}componentDidLoad(){e.setComponentLoaded(this)}disconnectedCallback(){d.disconnectMessages(this);
f.disconnectLocalized(this)}effectiveLocaleChange(){d.updateMessages(this,this.effectiveLocale)}async setFocus(){await e.componentFocusable(this);this.handleButton?.focus()}getAriaText(a){const {setPosition:h,setSize:k,label:l,messages:c,activated:m}=this;return c&&l&&"number"===typeof k&&"number"===typeof h?("label"===a?m?c.dragHandleChange:c.dragHandleIdle:m?c.dragHandleActive:c.dragHandleCommit).replace("{position}",h.toString()).replace("{itemLabel}",l).replace("{total}",k.toString()):null}render(){return b.h("span",
{"aria-label":this.getAriaText("label"),"aria-pressed":p.toAriaBoolean(this.activated),class:{handle:!0,["handle--activated"]:this.activated},onBlur:this.handleBlur,onKeyDown:this.handleKeyDown,role:"button",tabindex:"0",title:this.messages?.dragHandle,ref:a=>{this.handleButton=a}},b.h("calcite-icon",{icon:"drag",scale:"s"}))}static get assetsDirs(){return["assets"]}get el(){return this}static get watchers(){return{messages:["handleAriaTextChange"],label:["handleAriaTextChange"],activated:["handleAriaTextChange"],
setPosition:["handleAriaTextChange"],setSize:["handleAriaTextChange"],messageOverrides:["onMessagesChange"],effectiveLocale:["effectiveLocaleChange"]}}static get style(){return":host{display:flex}.handle{display:flex;cursor:move;align-items:center;justify-content:center;align-self:stretch;border-style:none;background-color:transparent;outline-color:transparent;color:var(--calcite-ui-border-input);padding-block:0.75rem;padding-inline:0.25rem;line-height:0}.handle:hover{background-color:var(--calcite-ui-foreground-2);color:var(--calcite-ui-text-1)}.handle:focus{color:var(--calcite-ui-text-1);outline:2px solid var(--calcite-ui-focus-color, var(--calcite-ui-brand));outline-offset:calc(\n            -2px *\n            calc(\n              1 -\n              2 * clamp(\n                0,\n                var(--calcite-ui-focus-offset-invert),\n                1\n              )\n            )\n          )}.handle--activated{background-color:var(--calcite-ui-foreground-3);color:var(--calcite-ui-text-1)}.handle calcite-icon{color:inherit}:host([hidden]){display:none}[hidden]{display:none}"}},
[1,"calcite-handle",{activated:[1540],dragHandle:[513,"drag-handle"],messages:[16],setPosition:[2,"set-position"],setSize:[2,"set-size"],label:[1],messageOverrides:[16],effectiveLocale:[32],defaultMessages:[32],setFocus:[64]}]);g();n.defineCustomElement=g});