// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define(["exports","./dom","./index"],function(C,m,ea){function R(c,e){var d=Object.keys(c);if(Object.getOwnPropertySymbols){var h=Object.getOwnPropertySymbols(c);e&&(h=h.filter(function(k){return Object.getOwnPropertyDescriptor(c,k).enumerable}));d.push.apply(d,h)}return d}function S(c){for(var e=1;e<arguments.length;e++){var d=null!=arguments[e]?arguments[e]:{};e%2?R(Object(d),!0).forEach(function(h){var k=d[h];a:if("object"===typeof h&&null!==h){var z=h[Symbol.toPrimitive];if(void 0!==z){h=z.call(h,
"string");if("object"!==typeof h)break a;throw new TypeError("@@toPrimitive must return a primitive value.");}h=String(h)}h="symbol"===typeof h?h:String(h);h in c?Object.defineProperty(c,h,{value:k,enumerable:!0,configurable:!0,writable:!0}):c[h]=k}):Object.getOwnPropertyDescriptors?Object.defineProperties(c,Object.getOwnPropertyDescriptors(d)):R(Object(d)).forEach(function(h){Object.defineProperty(c,h,Object.getOwnPropertyDescriptor(d,h))})}return c}var T={activateTrap:function(c,e){if(0<c.length){var d=
c[c.length-1];d!==e&&d.pause()}d=c.indexOf(e);-1!==d&&c.splice(d,1);c.push(e)},deactivateTrap:function(c,e){e=c.indexOf(e);-1!==e&&c.splice(e,1);0<c.length&&c[c.length-1].unpause()}},D=function(c){return"Tab"===(null===c||void 0===c?void 0:c.key)||9===(null===c||void 0===c?void 0:c.keyCode)},fa=function(c){return D(c)&&!c.shiftKey},ha=function(c){return D(c)&&c.shiftKey},U=function(c,e){var d=-1;c.every(function(h,k){return e(h)?(d=k,!1):!0});return d},E=function(c){for(var e=arguments.length,d=Array(1<
e?e-1:0),h=1;h<e;h++)d[h-1]=arguments[h];return"function"===typeof c?c.apply(void 0,d):c},K=function(c){return c.target.shadowRoot&&"function"===typeof c.composedPath?c.composedPath()[0]:c.target},ia=[],ka=function(c,e){var d=(null===e||void 0===e?void 0:e.document)||document,h=(null===e||void 0===e?void 0:e.trapStack)||ia,k=S({returnFocusOnDeactivate:!0,escapeDeactivates:!0,delayInitialFocus:!0,isKeyForward:fa,isKeyBackward:ha},e),z=[],w=[],p=[],N=null,u=null,q=!1,x=!1,O=void 0,L=void 0,r=function(l,
a,b){return l&&void 0!==l[a]?l[a]:k[b||a]},B=function(l,a){var b="function"===typeof(null===a||void 0===a?void 0:a.composedPath)?a.composedPath():void 0;return w.findIndex(function(f){var g=f.container;f=f.tabbableNodes;return g.contains(l)||(null===b||void 0===b?void 0:b.includes(g))||f.find(function(n){return n===l})})},F=function(l){var a=k[l];if("function"===typeof a){for(var b=arguments.length,f=Array(1<b?b-1:0),g=1;g<b;g++)f[g-1]=arguments[g];a=a.apply(void 0,f)}!0===a&&(a=void 0);if(!a){if(void 0===
a||!1===a)return a;throw Error("`".concat(l,"` was specified but was not a node, or did not return a node"));}b=a;if("string"===typeof a&&(b=d.querySelector(a),!b))throw Error("`".concat(l,"` as selector refers to no known node"));return b},G=function(){var l=F("initialFocus");if(!1===l)return!1;void 0!==l&&m.isFocusable(l,k.tabbableOptions)||(l=0<=B(d.activeElement)?d.activeElement:(l=p[0])&&l.firstTabbableNode||F("fallbackFocus"));if(!l)throw Error("Your focus-trap needs to have at least one focusable element");
return l},I=function(){w=z.map(function(l){var a=m.tabbable(l,k.tabbableOptions),b=m.focusable(l,k.tabbableOptions),f=0<a.length?a[0]:void 0,g=0<a.length?a[a.length-1]:void 0,n=b.find(function(v){return m.isTabbable(v)}),t=b.slice().reverse().find(function(v){return m.isTabbable(v)}),H=!!a.find(function(v){return 0<m.getTabIndex(v)});return{container:l,tabbableNodes:a,focusableNodes:b,posTabIndexesFound:H,firstTabbableNode:f,lastTabbableNode:g,firstDomTabbableNode:n,lastDomTabbableNode:t,nextTabbableNode:function(v){var V=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,W=a.indexOf(v);return 0>W?V?b.slice(b.indexOf(v)+1).find(function(P){return m.isTabbable(P)}):b.slice(0,b.indexOf(v)).reverse().find(function(P){return m.isTabbable(P)}):a[W+(V?1:-1)]}}});p=w.filter(function(l){return 0<l.tabbableNodes.length});if(0>=p.length&&!F("fallbackFocus"))throw Error("Your focus-trap must have at least one container with at least one tabbable node in it at all times");if(w.find(function(l){return l.posTabIndexesFound})&&
1<w.length)throw Error("At least one node with a positive tabindex was found in one of your focus-trap's multiple containers. Positive tabindexes are only supported in single-container focus-traps.");},A=function b(a){!1!==a&&a!==d.activeElement&&(a&&a.focus?(a.focus({preventScroll:!!k.preventScroll}),u=a,a.tagName&&"input"===a.tagName.toLowerCase()&&"function"===typeof a.select&&a.select()):b(G()))},X=function(a){var b=F("setReturnFocus",a);return b?b:!1===b?!1:a},Y=function(a){var b=a.target,f=
a.event;a=a.isBackward;var g=void 0===a?!1:a;b=b||K(f);I();a=null;if(0<p.length){var n=B(b,f),t=0<=n?w[n]:void 0;0>n?a=g?p[p.length-1].lastTabbableNode:p[0].firstTabbableNode:g?(g=U(p,function(H){return b===H.firstTabbableNode}),0>g&&(t.container===b||m.isFocusable(b,k.tabbableOptions)&&!m.isTabbable(b,k.tabbableOptions)&&!t.nextTabbableNode(b,!1))&&(g=n),0<=g?(f=p[0===g?p.length-1:g-1],a=0<=m.getTabIndex(b)?f.lastTabbableNode:f.lastDomTabbableNode):D(f)||(a=t.nextTabbableNode(b,!1))):(g=U(p,function(H){return b===
H.lastTabbableNode}),0>g&&(t.container===b||m.isFocusable(b,k.tabbableOptions)&&!m.isTabbable(b,k.tabbableOptions)&&!t.nextTabbableNode(b))&&(g=n),0<=g?(f=p[g===p.length-1?0:g+1],a=0<=m.getTabIndex(b)?f.firstTabbableNode:f.firstDomTabbableNode):D(f)||(a=t.nextTabbableNode(b)))}else a=F("fallbackFocus");return a},M=function(a){var b=K(a);0<=B(b,a)||(E(k.clickOutsideDeactivates,a)?y.deactivate({returnFocus:k.returnFocusOnDeactivate}):E(k.allowOutsideClick,a)||a.preventDefault())},Z=function(a){var b=
K(a),f=0<=B(b,a);if(f||b instanceof Document)f&&(u=b);else{a.stopImmediatePropagation();a=!0;if(u)if(0<m.getTabIndex(u)){if(b=B(u),b=w[b].tabbableNodes,0<b.length&&(f=b.findIndex(function(n){return n===u}),0<=f))if(k.isKeyForward(L)){if(f+1<b.length){var g=b[f+1];a=!1}}else 0<=f-1&&(g=b[f-1],a=!1)}else w.some(function(n){return n.tabbableNodes.some(function(t){return 0<m.getTabIndex(t)})})||(a=!1);else a=!1;a&&(g=Y({target:u,isBackward:k.isKeyBackward(L)}));g?A(g):A(u||G())}L=void 0},ja=function(a){var b=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1;L=a;if(b=Y({event:a,isBackward:b}))D(a)&&a.preventDefault(),A(b)},aa=function(a){"Escape"!==(null===a||void 0===a?void 0:a.key)&&"Esc"!==(null===a||void 0===a?void 0:a.key)&&27!==(null===a||void 0===a?void 0:a.keyCode)||!1===E(k.escapeDeactivates,a)?(k.isKeyForward(a)||k.isKeyBackward(a))&&ja(a,k.isKeyBackward(a)):(a.preventDefault(),y.deactivate())},ba=function(a){var b=K(a);0<=B(b,a)||E(k.clickOutsideDeactivates,a)||E(k.allowOutsideClick,
a)||(a.preventDefault(),a.stopImmediatePropagation())},ca=function(){if(q)return T.activateTrap(h,y),O=k.delayInitialFocus?setTimeout(function(){A(G())},0):A(G()),d.addEventListener("focusin",Z,!0),d.addEventListener("mousedown",M,{capture:!0,passive:!1}),d.addEventListener("touchstart",M,{capture:!0,passive:!1}),d.addEventListener("click",ba,{capture:!0,passive:!1}),d.addEventListener("keydown",aa,{capture:!0,passive:!1}),y},da=function(){if(q)return d.removeEventListener("focusin",Z,!0),d.removeEventListener("mousedown",
M,!0),d.removeEventListener("touchstart",M,!0),d.removeEventListener("click",ba,!0),d.removeEventListener("keydown",aa,!0),y};e=function(a){a.some(function(b){return Array.from(b.removedNodes).some(function(f){return f===u})})&&A(G())};var Q="undefined"!==typeof window&&"MutationObserver"in window?new MutationObserver(e):void 0,J=function(){Q&&(Q.disconnect(),q&&!x&&z.map(function(a){Q.observe(a,{subtree:!0,childList:!0})}))};var y={get active(){return q},get paused(){return x},activate:function(a){if(q)return this;
var b=r(a,"onActivate"),f=r(a,"onPostActivate"),g=r(a,"checkCanFocusTrap");g||I();q=!0;x=!1;N=d.activeElement;null===b||void 0===b?void 0:b();a=function(){g&&I();ca();J();null===f||void 0===f?void 0:f()};if(g)return g(z.concat()).then(a,a),this;a();return this},deactivate:function(a){if(!q)return this;var b=S({onDeactivate:k.onDeactivate,onPostDeactivate:k.onPostDeactivate,checkCanReturnFocus:k.checkCanReturnFocus},a);clearTimeout(O);O=void 0;da();x=q=!1;J();T.deactivateTrap(h,y);var f=r(b,"onDeactivate"),
g=r(b,"onPostDeactivate");a=r(b,"checkCanReturnFocus");var n=r(b,"returnFocus","returnFocusOnDeactivate");null===f||void 0===f?void 0:f();b=function(){setTimeout(function(){n&&A(X(N));null===g||void 0===g?void 0:g()},0)};if(n&&a)return a(X(N)).then(b,b),this;b();return this},pause:function(a){if(x||!q)return this;var b=r(a,"onPause");a=r(a,"onPostPause");x=!0;null===b||void 0===b?void 0:b();da();J();null===a||void 0===a?void 0:a();return this},unpause:function(a){if(!x||!q)return this;var b=r(a,"onUnpause");
a=r(a,"onPostUnpause");x=!1;null===b||void 0===b?void 0:b();I();ca();J();null===a||void 0===a?void 0:a();return this},updateContainerElements:function(a){z=[].concat(a).filter(Boolean).map(function(b){return"string"===typeof b?d.querySelector(b):b});q&&I();J();return this}};y.updateContainerElements(c);return y};const la=globalThis.calciteConfig?.focusTrapStack||[];C.Heading=(c,e)=>{const d=c.level?`h${c.level}`:"div";delete c.level;return ea.h(d,{...c},e)};C.activateFocusTrap=function(c,e){c.focusTrapDisabled||
c.focusTrap?.activate(e)};C.connectFocusTrap=function(c,e){const {el:d}=c,h=e?.focusTrapEl||d;h&&(c.focusTrap=ka(h,{clickOutsideDeactivates:!0,escapeDeactivates:!1,fallbackFocus:h,setReturnFocus:k=>{m.focusElement(k);return!1},...e?.focusTrapOptions,document:d.ownerDocument,tabbableOptions:m.tabbableOptions,trapStack:la}))};C.deactivateFocusTrap=function(c,e){c.focusTrap?.deactivate(e)};C.updateFocusTrapElements=function(c){c.focusTrap?.updateContainerElements(c.el)}});